name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  run-lint-checks:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Install goimports
        run: go install golang.org/x/tools/cmd/goimports@latest
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.1

      - name: Run Tests
        run: go test -v ./tests/...
